# Generated by Django 3.0.4 on 2020-04-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200410_0639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Destinations',
        ),
    ]
